### ISSUE TITLE
0.5

### ISSUE THREAD

**Issue by theimerj** [dystcz/lunar-api#19]
We have to upgrade and make sure that everything works with the new Lunar release.

- [x] Upgrade to Lunar 0.5
- [x] Fix tests
- [x] Introduce Github actions with sensible PHP and Laravel version support #31 
- [x] Extract payment gateway logic out of this package #33 
- [x] Wait for #27 (This [PR](https://github.com/lunarphp/lunar/pull/1243) will have to get merged.)

**Comment by tdwesten** [comment]
This is a great line-up voor version 0.4

**Comment by theimerj** [comment]
> This is an great lineup for version 0.4. It might be wise to fix the tests first, so we know what breaks after updating to Lunar 0.4.

Yes, this is the plan. 👍
